kind: pipeline
type: docker
name: mimishop-production-cicd

# Sử dụng Docker mirror để tránh timeout
clone:
  disable: false

steps:
  # 1. Build và Push Backend Image lên Docker Hub
  - name: build-and-push-backend
    image: plugins/docker
    settings:
      context: ./mimiStyle-backend/mimi/mimi
      dockerfile: ./mimiStyle-backend/mimi/mimi/Dockerfile
      repo: hoangduy20407/mimi-backend
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry-1.docker.io
      insecure: false
      debug: true
      # Sử dụng mirror
      mirror: https://mirror.gcr.io
    when:
      branch:
        - main

  # 2. Build và Push Frontend Image lên Docker Hub
  - name: build-and-push-frontend
    image: plugins/docker
    settings:
      context: ./mimiStyle-frontend
      dockerfile: ./mimiStyle-frontend/Dockerfile
      repo: hoangduy20407/mimi-frontend
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry-1.docker.io
      insecure: false
      debug: true
      # Sử dụng mirror
      mirror: https://mirror.gcr.io
    when:
      branch:
        - main

  # 3. Kết nối SSH vào VPS để triển khai (Deploy)
  - name: deploy-to-vps
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username: 
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 10m
      script:
        - cd /opt/mimi
        # Kéo bản mới nhất của 2 image vừa push xong
        - docker compose pull backend frontend
        # Khởi động lại chỉ 2 dịch vụ này, giữ nguyên MySQL và Nginx Proxy Manager
        - docker compose up -d backend frontend
        # Dọn dẹp các image cũ (dangling) để tránh đầy ổ cứng VPS
        - docker image prune -f
    when:
      branch:
        - main

# Drone sẽ chỉ chạy pipeline này khi push code vào nhánh main
trigger:
  branch:
    - main